# Generated by Django 4.1.7 on 2023-04-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetasapp', '0004_alter_receta_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
